ALTER TYPE "MenuItemType" ADD VALUE IF NOT EXISTS 'GROUP';
ALTER TYPE "MenuItemType" ADD VALUE IF NOT EXISTS 'SOUND';
ALTER TYPE "MenuItemType" ADD VALUE IF NOT EXISTS 'SHARE';
ALTER TYPE "MenuItemType" ADD VALUE IF NOT EXISTS 'LOGO';

ALTER TABLE "memories" ADD COLUMN "view_count" INTEGER NOT NULL DEFAULT 0;
